### ISSUE TITLE
WPF - Again Splitter....

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1137]
this is still the old issue, but here is three new buttons now to reproduce with Eto.Test:
[SplitterSection.zip](https://github.com/picoe/Eto/files/2130759/SplitterSection.zip)

My use case is not just to toggle visibility of a single panel, this is working, but to change visibility of two panels with one command. The problem is with Splitter.Position, which changes to 0 from a certain point on.
```
// added by Tom to demonstrate bug
// 1. click "1-2" -> both panels are visible         -> ok
// 2. click "2"   -> panel 2 is visible, panel 1 not -> ok
// 3. click "1"   -> panel 1 is visible, panel 2 not -> ok
// 4. click "1-2" -> both panels are visible, but splitterhandle-position is 0 now, so panel 1 is actually not visible

var show12 = new Button { Text = "1-2" };
show12.Click += delegate { splitter.Panel1.Visible = true; splitter.Panel2.Visible = true; };
var show1 = new Button { Text = "1" };
show1.Click += delegate { splitter.Panel1.Visible = true; splitter.Panel2.Visible = false; };
var show2 = new Button { Text = "2" };
show2.Click += delegate { splitter.Panel1.Visible = false; splitter.Panel2.Visible = true; };
```

**Comment by cwensley** [comment]
Thanks for the report and repro!  This should help greatly to fix the problem.

**Comment by TomQv** [comment]
Just checked mac, all fine there, seems to be a wpf-problem.
As far as I noticed while trying to debug something with Width/ActualWidth, which is 0 when the bug occurs.

**Comment by TomQv** [comment]
This fix would be a bit urgent, because we would need this functionality for a new app soon... ;)

**Comment by cwensley** [comment]
Hey @TomQv,

I can't seem to reproduce this issue (on develop branch).  Is it still not working for you?

![wpf-splitters-hiding](https://user-images.githubusercontent.com/367446/46189849-9fba9e00-c2a5-11e8-87ae-4b6a8b5bfcc8.gif)

**Comment by cwensley** [comment]
Hm, just re-read this part:
> both panels are visible, but splitterhandle-position is 0 now, so panel 1 is actually not visible

So, `Splitter.Position` property is returning `0`, even though it is showing the panel?

**Comment by TomQv** [comment]
Just do it in this order:

// 1. click "1-2" -> both panels are visible         -> ok
// 2. click "2"   -> panel 2 is visible, panel 1 not -> ok
// 3. click "1"   -> panel 1 is visible, panel 2 not -> ok
// 4. click "1-2" -> both panels are visible, but splitterhandle-position is 0 now, so the red panel has a width of 0 and the splitterhandle is sticking on the left side.
![2018-09-28 07_57_30-](https://user-images.githubusercontent.com/6605960/46190529-2dbd7580-c2f4-11e8-8a29-0daceda33369.png)

**Comment by cwensley** [comment]
@TomQv I did do it in that exact order, in the first part of that gif I attached..  You're using the latest develop branch?

**Comment by TomQv** [comment]
You're right, with the latest dev, its seems to be fine. 
When did you fix it? Maybe I missed it reading the commits.
I'm still on an older version because I was struggling to merge the latest dev into my project yesterday. Some things were broken. Anyway, will try again. Thank you.

**Comment by cwensley** [comment]
Hm, glad to hear it's working, it'd be interesting to find out what commit fixed it.  How old is the version you're using?

**Comment by TomQv** [comment]
Good question, in which file in the source is the version-info of the dev-build?

**Comment by TomQv** [comment]
Checking the dates, most files are from March 23, 2018, so quiet old.
The funny thing is, the file eto.wpf.forms.splitterhandler.cs is still the same.

Curtis, could you please do me a favour, if you maybe have some time, and have a look at [issue 1224](https://github.com/picoe/Eto/issues/1224)?

**Comment by cwensley** [comment]
@TomQv it's not easy to track down.  If you've built from source, you can look at the AssemblyVersion of the file to determine the date/time it was built.

Now that I've added some stuff to generate the AssemblyFileVersion during build, I might put the git sha in the informational version.. hm..

**Comment by cwensley** [comment]
>  if you maybe have some time, and have a look at issue 1224?

No promises, but I'll see what I can do..  I have some other bugs I'm working on with Mojave at the moment.

**Comment by TomQv** [comment]
> other bugs I'm working on with Mojave at the moment
Really? With Eto?
We also realized issues with our app with Mojave, we are using Open GL and some things with mouse-events are broken now, also have to check this today.

**Comment by cwensley** [comment]
> Really? With Eto?

Yeah, WebView and a problem with Splitter.  There was also a crashing issue with Slider that was fixed about month ago.

**Comment by TomQv** [comment]
> Hm, glad to hear it's working, it'd be interesting to find out what commit fixed it. How old is the version you're using?

Still not fine. In the scope of our app, its still the same bug.
Maybe, because we have much more complex ui inside the splitter and not just an empty panel. So maybe the wpf-layout-cycle takes longer and this confuses the splitter?

Anyway, I added the following check after "1-2":
```
public void MakeSureSplitterOk()
{
    var r = _splitter.RelativePosition;
    if (_splitter.Panel1.Visible && _splitter.Panel2.Visible && (r < 0.1 || r > 0.9))
        _splitter.RelativePosition = 0.5;
}
```
With this workaround its fine for us. 
We can close this issue, which seems to be not solvable with reasonable effort.

**Comment by cwensley** [comment]
Hm, not sure what to do about this one without a reliable repro.  Closing as suggested by @TomQv.

If you do end up figuring out a better repro, feel free to reopen or create a new issue.
