### ISSUE TITLE
[Mac] null properties bound to a GridColumn are rendered with the text "Field"

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1247]
On Mac if a property bound to a GridColumn is null the text "Field" is shown in the cell.

## Expected Behavior
null proprieties bound to a GridColumn should show an empty string in the cell

## Actual Behavior
null proprieties bound to a GridColumn show the text "Field" in the cell

## Steps to Reproduce the Problem

  1. run the following code, you will get this
![image](https://user-images.githubusercontent.com/21080030/48201586-eef2f480-e362-11e8-8a05-70ff1eb02f29.png)
  2. In order to work around the problem I tried to do the following: comment the row with:
```
Binding = Binding.Property<Data, string>(r => r.Col1)
```
and uncomment the row with:
```
Binding = Binding.Property<Data, string>(r => r.Col1 ?? string.Empty)
```
you will get this:
![image](https://user-images.githubusercontent.com/21080030/48201317-185f5080-e362-11e8-8340-05d2549502a4.png)
now for a null property I get an empty string, but I've lost the possibility to change the property editing the cell, in fact if I now click on the cell "click me" and edit something in the cell in the first column, the text does not go into the Data.Col1 property

So, is there a special binding that I can put here
```
Binding = Binding.Property<Data, string>(r => r.Col1)
```
in order to bind r.Col1 without seeing the "field" text?

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Forms;
using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace VisualSEO.EtoFormGui
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			new Application(Platform.Detect).Run(new MyMainForm());
		}

		public class MyMainForm : Form
		{
			public MyMainForm()
			{
				GridColumn col;
				GridView grid = new GridView() { Width = 200, Height = 100 };
				grid.Columns.Add(col = new GridColumn {
					DataCell = new TextBoxCell()
					{
						Binding = Binding.Property<Data, string>(r => r.Col1)
						//Binding = Binding.Property<Data, string>(r => r.Col1 ?? string.Empty)
					}, Editable = false, HeaderText = "Text to edit" });
				grid.Columns.Add(new GridColumn { DataCell = new TextBoxCell("Col2"), Editable = false });
				ObservableCollection<Data> model = new ObservableCollection<Data>();
				model.Add(new Data { Col1 = null, Col2 = "click me" });
				model.Add(new Data { Col1 = null, Col2 = "click me" });
				model.Add(new Data { Col1 = null, Col2 = "click me" });
				model.Add(new Data { Col1 = null, Col2 = "click me" });
				grid.DataStore = model;
				grid.CellClick += (sender, e) =>
				{
					if (e.Column == 1)
					{
						Task.Run(() =>
						{
							Application.Instance.Invoke(() =>
							{
								col.Editable = true;
								grid.BeginEdit(e.Row, 0);
							});
						});
					}
				};
				grid.CellEdited += (sender, e) =>
				{
					col.Editable = false;
				};
				Content = grid;
			}

			public class Data
			{
				public string Col1 { get; set; }
				public string Col2 { get; set; }
			}
		}
	}
}
```

## Specifications

  - Version: 2.4.9999
  - Platform(s): tested with XamMac2
  - Operating System(s): tested on macOS 10.13

**Comment by cwensley** [comment]
Hey @msasso69, thanks for reporting the issue.  It should be an easy fix, but in regards to how you can keep the two-way binding functionality but still modify the value you can use the `Convert` method like so:

```c#
Binding.Property((Data r) => r.Col1).Convert(s => s ?? string.Empty, s => s)
```

The reason the two-way binding is broken in your binding is that doing the logic in the property binding negates its ability to determine how to set the value as you are no longer binding to a property, but a piece of code that executes.  

Another way you could do it is to specify how the value is set using `Binding.Delegate`, however this still won't bind to change events in your data model (not that it does in the GridView yet anyway, so it is moot in this case).

```c#
Binding.Delegate((Data r) => r.Col1 ?? string.Empty, (r, v) => r.Col1 = v)
```

**Comment by cwensley** [comment]
Should now be fixed!  Thanks again!

**Comment by msasso69** [comment]
Thanks for the quick fix! :)
But when you say "however this still won't bind to change events in your data model (not that it does in the GridView yet anyway," you mean that changes in the model are not detected by the GridView / TreeGridView?
In fact I've already noticed it but I was thinking of a bug in my code (like a wrong implementation of an interface like for example IPropertyChanged).
Do you have plans to also support that changes in the the model reflect what is shown in the grids?
