### ISSUE TITLE
GridView ReloadData jumps to top on Gtk3

### ISSUE THREAD

**Issue by Sejsel** [picoe/Eto#1290]
## Expected Behavior

Calling ReloadData on a GridView should not move it and ideally should not be noticeable at all. 

## Actual Behavior

On the GTK3 platform it instead scrolls to the top of the gridview. On WPF this does not happen, instead it only gets defocused.

## Steps to Reproduce the Problem

  1. Launch Eto.Test.Gtk3
  2. Open the Controls>GridView section
  3. Scroll down in the GridView
  4. Click on ReloadData

  - Version: commit fc2d569eb21 (current develop HEAD). 2.4.1 as well.
  - Platform(s): Gtk3
  - Operating System(s): Arch Linux with gtk3 3.24.2+1+g2905fc861a-1

**Comment by cwensley** [comment]
`GridView.ReloadData(rows)` should now work without scrolling to the top!  Thanks again for reporting the issue.

**Comment by Sejsel** [comment]
Thank you very much for the fix! Will try this out when I have a bit of time.

**Comment by Sejsel** [comment]
Unfortunately, the scrolling still happens even on 2.7.0 with `GridView.ReloadData()`
